/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f7",
        "primary-fixed-dim": "#ffb3af",
        "secondary-fixed-dim": "#77dd6a",
        "on-secondary-fixed": "#002201",
        "surface-container": "#ffe9e7",
        "on-error-container": "#93000a",
        "outline-variant": "#e2bebc",
        "on-background": "#261817",
        "primary": "#b5242c",
        "surface-container-high": "#fde2e0",
        "surface-container-low": "#fff0ef",
        "surface-bright": "#fff8f7",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#59dcb0",
        "tertiary": "#006c50",
        "on-tertiary-container": "#003425",
        "surface-variant": "#f8dcda",
        "inverse-surface": "#3d2c2b",
        "on-tertiary-fixed-variant": "#00513c",
        "error-container": "#ffdad6",
        "primary-container": "#ff5b5b",
        "inverse-primary": "#ffb3af",
        "on-surface-variant": "#5a403f",
        "surface-dim": "#efd4d2",
        "on-primary-fixed-variant": "#920218",
        "tertiary-container": "#00a87f",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002116",
        "secondary-container": "#8ff780",
        "surface-container-highest": "#f8dcda",
        "tertiary-fixed": "#78f9cb",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdad7",
        "on-primary-container": "#61000c",
        "on-secondary-container": "#00730d",
        "secondary-fixed": "#92fa83",
        "background": "#fff8f7",
        "outline": "#8e706e",
        "secondary": "#006e0c",
        "inverse-on-surface": "#ffedeb",
        "on-secondary-fixed-variant": "#005307",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#410005",
        "surface-tint": "#b5242c",
        "on-surface": "#261817"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "display-lg": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        serif: ['Instrument Serif', 'serif'],
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
